### PR TITLE
Install fixes

### PR DESCRIPTION
**Pull request by jefffriesen**
I added a few things for the install process. I only edited the first two files in this diff (README.md and package.son) so not sure why all of the other files came in with this PR. I'm happy to redo this if you have suggestions.

### CODE REVIEW

**Comment by ivan-kleshnin** [comment]
Hi, @jefffriesen 
First, to note: I plan to update this repo soon, I'm just running out of time with my other work.
I'm going to completely remove `static` folder from VCS. I'm really tired to solve "conflicts" in minimized files. As this repo is not a library, but an app there is a little benefit to keep distributives under Git but there are a lot of drawbacks. What do you think about it?

**Comment by jefffriesen** [comment]
Ok. If it's too complicated to merge this PR we can cancel it and you could just make the changes yourself. Whatever is easiest.

**Comment by ivan-kleshnin** [comment]
Also about vendor deps:

`sizzle` -- will we need this? I never used that lib, do you think it's better than `cheerio`?
`requirejs` -- don't think it's required, as I'm going to rewrite this repo in `webpack`. 
`qunit, sinon` -- again, I don't know yet what tests will be used here.

**Comment by ivan-kleshnin** [comment]
So I think it's better to close this. I'm gonna give this repo a kick tomorrow.

**Comment by jefffriesen** [comment]
I think there is a little confusion. I didn't touch (intentionally) this file: `static/vendors/jquery/.bower.json` 

I only made these changes:

README.md:
`Note that `bin/install` depends on `greadlink` being in your path. On OSX, you can run `brew install coreutils` to install it. (more info)[http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac]`

package.json:

```
"body-parser": "^1.12.4",
"cookie-parser": "^1.3.4",
"express": "^4.12.3",
```

Ignore everything below that

**Comment by ivan-kleshnin** [comment]
Yeah but here we have 93 changed files. That's because you created dists for your instance and they are under VCS. And I can't even cherrypick them because they are in the single commit. That's what I've talked about above. Actually, this `greadlink` will be also no longer required in the new simplified install I gonna drop today :smile:

**Comment by jefffriesen** [comment]
Ok, sorry about that. There are still a couple missing dependencies in package.json that you may want to include if you haven't already.

**Comment by ivan-kleshnin** [comment]
@jefffriesen I made a total repo reset. Hope it's more accessible now. 
You're in the collaborators already :wink:

**Comment by jefffriesen** [comment]
Great. I'll check it out.

**Pull request closed without merging**
